//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samsung_Order
    {
        public Samsung_Order()
        {
            this.Samsung_OrderItem = new HashSet<Samsung_OrderItem>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> totalPrice { get; set; }
    
        public virtual ICollection<Samsung_OrderItem> Samsung_OrderItem { get; set; }
        public virtual Samsung_User Samsung_User { get; set; }
    }
}
