//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nike_User
    {
        

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ScreenName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string emailAddress { get; set; }
        public string Password { get; set; }

        public Nike_User(string firstName, string lastName, string screenName, string gender, int? zipcode, string emailAddress, DateTime? dateOfBirth, string password)
        {
            FirstName = firstName;
            LastName = lastName;
            ScreenName = screenName;
            Gender = gender;
            Zipcode = zipcode;
            this.emailAddress = emailAddress;
            DateOfBirth = dateOfBirth;
            Password = password;
        }

       public Nike_User()
        {
        }
    }
    
}
