//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nike_Product
    {
        public Nike_Product()
        {
            this.Nike_Images = new HashSet<Nike_Images>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Size { get; set; }
    
        public virtual Nike_Category Nike_Category { get; set; }
        public virtual ICollection<Nike_Images> Nike_Images { get; set; }
    }
}
