//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NikeDBEntities : DbContext
    {
        public NikeDBEntities()
            : base("name=NikeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nike_Category> Nike_Category { get; set; }
        public virtual DbSet<Nike_Images> Nike_Images { get; set; }
        public virtual DbSet<Nike_Product> Nike_Product { get; set; }
        public virtual DbSet<Nike_User> Nike_User { get; set; }
    }
}
