//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samsung_Product
    {
        public Samsung_Product()
        {
            this.Samsung_Images = new HashSet<Samsung_Images>();
            this.Samsung_Order = new HashSet<Samsung_Order>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string color { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> stock { get; set; }
        public string details { get; set; }
    
        public virtual Samsung_Category Samsung_Category { get; set; }
        public virtual ICollection<Samsung_Images> Samsung_Images { get; set; }
        public virtual ICollection<Samsung_Order> Samsung_Order { get; set; }
    }
}
