//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samsung_User
    {
        public Samsung_User()
        {
            this.Samsung_Order = new HashSet<Samsung_Order>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> zipCode { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string emailAddress { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Samsung_Order> Samsung_Order { get; set; }
    }
}
