//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samsung.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samsung_Order
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> productId { get; set; }
    
        public virtual Samsung_Product Samsung_Product { get; set; }
        public virtual Samsung_User Samsung_User { get; set; }
    }
}
